apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-python-app.fullname" . }}
  labels:
    app: {{ include "my-python-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-python-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-python-app.name" . }}
    spec:
      containers:
      - name: my-python-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
